# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-20T02:41:46Z"
  labels:
    app: wordpress-pod
  name: wordpress-pod
spec:
  containers:
    - args:
        - mariadbd
      env:
        - name: MYSQL_USER
          value: wordpress
        - name: HOSTNAME
          value: 694f91aacb2c
        - name: HOME
          value: /root
        - name: MYSQL_PASSWORD
          value: wordpress
        - name: TERM
          value: xterm
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
      image: docker.io/library/mariadb:latest
      name: jovialvillani-podified
      ports:
        - containerPort: 3306
          hostPort: 3306
        - containerPort: 80
          hostPort: 9000
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: 14c529d696928cce9b5983c5657723cbc4c651ea48b9e2eb1a8133c4f140aea7-pvc
    - args:
        - apache2-foreground
      env:
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: TERM
          value: xterm
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: PHP_CPPFLAGS
          value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS
        - name: PHP_CFLAGS
          value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS
        - name: HOSTNAME
          value: 6523b6469218
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: HOME
          value: /root
      image: docker.io/library/wordpress:latest
      name: romanticborg-podified
      volumeMounts:
        - mountPath: /var/www/html
          name: 4759f5e6e0a7ae18e84500c43f415cee47380f92ec6acc081dba4f23d30db6bb-pvc
  volumes:
    - name: 14c529d696928cce9b5983c5657723cbc4c651ea48b9e2eb1a8133c4f140aea7-pvc
      persistentVolumeClaim:
        claimName: 14c529d696928cce9b5983c5657723cbc4c651ea48b9e2eb1a8133c4f140aea7
    - name: 4759f5e6e0a7ae18e84500c43f415cee47380f92ec6acc081dba4f23d30db6bb-pvc
      persistentVolumeClaim:
        claimName: 4759f5e6e0a7ae18e84500c43f415cee47380f92ec6acc081dba4f23d30db6bb
